name: Register Pipeline

on:
  push:
    branches: "master"

jobs:
  run:
    name: Pangeo-Forge CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
            python -m pip install git+https://github.com/pangeo-forge/pangeo-forge

      - name: Run Pipeline
        run: |
            prefect auth login --token ${{ secrets.PREFECT_ACCESS_TOKEN }}
            pangeo-forge check
            pangeo-forge register

            # Run flow
            # Watch this URL
            pangeo-forge run
