name: Test Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/pangeo-forge/pangeo-forge
    - name: Test with pytest
      run: |
        PYTHONPATH=recipe python ./.github/workflows/scripts/test_pipeline.py
